process_dict = {
    r"phường\."     : "phường",
    r"quận\."       : "quận",
    r"(?<=phường\s\d)q(?=\d)"   : " quận ",
    r"(?<=phường\s\d\d)q(?=\d)" : " quận ",
    r"thành phố\."  : "thành phố",
    r"tỉnh\."       : "tỉnh",
    r"t\.\s+x[ãa]\.*"  : "thị xã",
    r"[đd]/c"       : "địa chỉ",
    r"[đd]c\s*:"    : "địa chỉ",
    r"\st\."          : " tỉnh",
    r"^t\."          : " tỉnh",
    r'địa\schỉhị'   : "địa chỉ",
    r'buôn\s+ma\s+thuộc': "buôn mê thuộc",
    r'buon\s+ma\s+thuoc': "buôn mê thuộc",
    r'bao\snhi[eẻẹệ][uhiy]' : "bao nhiêu",
    r'(?<=chất\s)v[ãa]i'    : "vải",
    r'v[aã]i\s(?=g[ìi])'    : "vải ",
    r'(?<=m[ặaạă][ct]\s)[sz]a[i]'  : "size",
    r'[sz]ai\s?(?=[lms0-9])'   : "size ",
    r'nhi[êe]?u v[iị]'      : "nhiêu vậy",
    r'bu\s[đd]i[eệ]n'       : "bưu điện",
    r'(?<=(bao|bây))\sh'    : " giờ",
    r'(?<=\d)jo'            : " giờ",
    r'(?<=\d)(tp)?hcm'      : " thành phố hồ chí minh",
    r'thị\strấn\.?\shuế'    : "thừa thiên huế",
    r'b[ìi]nh\sth[ạa]ch'    : "bình thạnh",
    r's[aà]i\s?g[òo]n'      : "thành phố hồ chí minh",
    r'c[aá]ch\sm[aạ]ng\sth[aá]ng\s8': "cách mạng tháng tám",
    r'ph[uư][oơớ]c\slong\sbạn': "phước long b",
    r't[aă]ng\snh[oơ]n\sph[uú]\sbạn': "tăng nhơn phú b",
    r'v[iĩ]nh\sl[oọôộ]c\sbạn'    : "vĩnh lộc b",
    r'b[iì]nh\sh[uư]ng\sh[oò][aà]\sbạn'    : "bình hưng hòa b",
    r'b[iì]nh\str[iị]\s[dđ][oô]ng\sbạn' : "bình trị đông b",
    r'[dđ][oô]ng\sl[ợơo]i\sbạn'     : "đông lợi b",
    r'\b30/4\b' : "ba mươi tháng tư",
    r'\b3/2\b'  : "ba tháng hai",
    r'(?<=[0-9])\s?máy' : " mấy",
    r'eo(?=\d)': "eo ",
    r'nặng(?=\d)' : "nặng ",
    r'cao(?=\d)' : "cao ",
    r'bộ\snay' : "bộ này",
    r'\b[dđ]k\s*(k|kh[oô]ng)\b' : 'được không',
    r'\b[dđ]k\s*(?!(k|kh[oô]ng))\b' : 'được không '
}